metronic-settings:
  name: metronic
  layoutDir: layout/
  direction: ltr
  modeSwitchEnabled: true
  modeDefault: light
  assetsDir: https://static.d2e.life/api-doc-automation/static/assets/
  iconType: duotone
  defaultLayout: default-dark-sidebar
  assets:
    favicon: media/logos/favicon.ico
    fonts:
      - https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700
      - https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap
    css:
      - plugins/global/plugins.bundle.css
      - css/style.bundle.css
    js:
      - plugins/global/plugins.bundle.js
      - js/scripts.bundle.js
  vendors:
    - name: datatables
      css:
        - plugins/custom/datatables/datatables.bundle.css
      js:
        - plugins/custom/datatables/datatables.bundle.js
    - name: formrepeater
      js:
        - plugins/custom/formrepeater/formrepeater.bundle.js
    - name: fullcalendar
      css:
        - plugins/custom/fullcalendar/fullcalendar.bundle.css
      js:
        - plugins/custom/fullcalendar/fullcalendar.bundle.js
    - name: flotcharts
      js:
        - plugins/custom/flotcharts/flotcharts.bundle.js
    - name: google-jsapi
      js:
        - //www.google.com/jsapi
    - name: tinymce
      js:
        - plugins/custom/tinymce/tinymce.bundle.js
    - name: ckeditor-classic
      js:
        - plugins/custom/ckeditor/ckeditor-classic.bundle.js
    - name: ckeditor-inline
      js:
        - plugins/custom/ckeditor/ckeditor-inline.bundle.js
    - name: ckeditor-balloon
      js:
        - plugins/custom/ckeditor/ckeditor-balloon.bundle.js
    - name: ckeditor-balloon-block
      js:
        - plugins/custom/ckeditor/ckeditor-balloon-block.bundle.js
    - name: ckeditor-document
      js:
        - plugins/custom/ckeditor/ckeditor-document.bundle.js
    - name: draggable
      js:
        - plugins/custom/draggable/draggable.bundle.js
    - name: fslightbox
      js:
        - plugins/custom/fslightbox/fslightbox.bundle.js
    - name: jkanban
      css:
        - plugins/custom/jkanban/jkanban.bundle.css
      js:
        - plugins/custom/jkanban/jkanban.bundle.js
    - name: typedjs
      js:
        - plugins/custom/typedjs/typedjs.bundle.js
    - name: cookiealert
      css:
        - plugins/custom/cookiealert/cookiealert.bundle.css
      js:
        - plugins/custom/cookiealert/cookiealert.bundle.js
    - name: cropper
      css:
        - plugins/custom/cropper/cropper.bundle.css
      js:
        - plugins/custom/cropper/cropper.bundle.js
    - name: vis-timeline
      css:
        - plugins/custom/vis-timeline/vis-timeline.bundle.css
      js:
        - plugins/custom/vis-timeline/vis-timeline.bundle.js
    - name: jstree
      css:
        - plugins/custom/jstree/jstree.bundle.css
      js:
        - plugins/custom/jstree/jstree.bundle.js
    - name: prismjs
      css:
        - plugins/custom/prismjs/prismjs.bundle.css
      js:
        - plugins/custom/prismjs/prismjs.bundle.js
    - name: leaflet
      css:
        - plugins/custom/leaflet/leaflet.bundle.css
      js:
        - plugins/custom/leaflet/leaflet.bundle.js
    - name: amcharts
      js:
        - https://cdn.amcharts.com/lib/5/index.js
        - https://cdn.amcharts.com/lib/5/xy.js
        - https://cdn.amcharts.com/lib/5/percent.js
        - https://cdn.amcharts.com/lib/5/radar.js
        - https://cdn.amcharts.com/lib/5/themes/Animated.js
    - name: amcharts-maps
      js:
        - https://cdn.amcharts.com/lib/5/index.js
        - https://cdn.amcharts.com/lib/5/map.js
        - https://cdn.amcharts.com/lib/5/geodata/worldLow.js
        - https://cdn.amcharts.com/lib/5/geodata/continentsLow.js
        - https://cdn.amcharts.com/lib/5/geodata/usaLow.js
        - https://cdn.amcharts.com/lib/5/geodata/worldTimeZonesLow.js
        - https://cdn.amcharts.com/lib/5/geodata/worldTimeZoneAreasLow.js
        - https://cdn.amcharts.com/lib/5/themes/Animated.js
    - name: amcharts-stock
      js:
        - https://cdn.amcharts.com/lib/5/index.js
        - https://cdn.amcharts.com/lib/5/xy.js
        - https://cdn.amcharts.com/lib/5/themes/Animated.js
    - name: bootstrap-select
      css:
        - plugins/custom/bootstrap-select/bootstrap-select.bundle.css
      js:
        - plugins/custom/bootstrap-select/bootstrap-select.bundle.js
